google.charts.load("current", {
    "packages": ["geochart"],
    "mapsApiKey": "AIzaSyA2oWm_JyAFYAD4io8qS9AUupNwxyIcDQM"
});

google.charts.setOnLoadCallback(drawMap);

function drawMap() {
    var data = google.visualization.arrayToDataTable([
        ['Country', 'Value'],
        ["French Guiana",0],
        ["Suriname",0],
        ["Falkland Islands",0],
        ["Belize",0],
        ["North Korea",0],
        ["Western Sahara",0],
        ["Sierra Leone",0],
        ["Liberia",0],
        ["Eritrea",0],
        ["Central African Republic",0],
        ["Republic of Congo",0],
        ["Guinea-Bissau",0],
        ["Lesotho",0],
        ["Swaziland",0],
        ["Burkina Faso",0],
        ["Togo",0],
        ["Equatorial Guinea",0],
        ["Djibouti",0],
        ["Rwanda",0],
        ["Burundi",0],
        ["Malawi",0],
        ["Timor-Leste",0],
        ["Solomon Islands",0],
        ["Vanuatu",0],
        ["Svalbard",0],
        ["Bhutan",0],
        ["Democratic Republic of the Congo",0],
        ["Liechtenstein",0],
        ["Maldives",0],
        ["Sudan",0],
        ["Zimbabwe",0],
        ["Mauritania",0],
        ["Mozambique",0],
        ["Nigeria",0],
        ["Swaziland",0],
        ["Tanzania",0],
        ["Iraq",0],
        ["Guyana",0],
        ["Namibia",0],
        ["Senegal",0],
        ["Turkmenistan",0],
        ["Afghanistan",0],
        ["Andorra",0],
        ["Fiji",0],
        ["Gabon",0],
        ["Uzbekistan",0],
        ["Cameroon",0],
        ["Cuba",0],
        ["Faroe Islands",0],
        ["El Salvador",0],
        ["Caribbean",0],
        ["Ethiopia",0],
        ["Mongolia",0],
        ["Puerto Rico",0],
        ["Samoa",0],
        ["Myanmar",0],
        ["Nicaragua",0],
        ["Seychelles",0],
        ["Tajikistan",0],
        ["Dominican Republic",0],
        ["Guinea",0],
        ["Barbados",0],
        ["CI",0],
        ["Laos",0],
        ["Libya",0],
        ["Panama",0],
        ["Bahrain",0],
        ["Benin",0],
        ["Ghana",0],
        ["Haiti",0],
        ["Montenegro",0],
        ["Somalia",0],
        ["Syria",0],
        ["Ecuador",0],
        ["Honduras",0],
        ["Madagascar",0],
        ["Papua New Guinea",0],
        ["Tunisia",0],
        ["Angola",0],
        ["Botswana",0],
        ["Cyprus",0],
        ["Algeria",0],
        ["Bahamas",0],
        ["New Caledonia",0],
        ["Uganda",0],
        ["Yemen",0],
        ["Zambia",0],
        ["Antarctica",0],
        ["Paraguay",0],
        ["Jamaica",0],
        ["Palestine",0],
        ["Bolivia",0],
        ["Bosnia and Herzegovina",0],
        ["Vietnam",0],
        ["Kenya",0],
        ["Luxembourg",0],
        ["Niger",0],
        ["Kuwait",0],
        ["Hawaii",0],
        ["Scotland",0],
        ["Cambodia",0],
        ["Uruguay",0],
        ["Kyrgyzstan",0],
        ["Saudi Arabia",0],
        ["Indonesia",0],
        ["Azerbaijan",0],
        ["United Arab Emirates",0],
        ["Mauritius",0],
        ["Morocco",0],
        ["Albania",0],
        ["South Korea",0],
        ["Kazakhstan",0],
        ["Macedonia",0],
        ["Venezuela",0],
        ["Taiwan",0],
        ["Qatar",0],
        ["Jordan",0],
        ["Iceland",0],
        ["Guatemala",0],
        ["Costa Rica",0],
        ["Hong Kong",0],
        ["San Marino",0],
        ["Colombia",0],
        ["Moldova",0],
        ["Armenia",0],
        ["Malta",0],
        ["Nepal",0],
        ["Lebanon",0],
        ["Malaysia",0],
        ["Serbia",0],
        ["Peru",0],
        ["Trinidad and Tobago",0],
        ["Lithuania",0],
        ["Estonia",0],
        ["Georgia",0],
        ["Iran",0],
        ["Chile",0],
        ["Latvia",0],
        ["Thailand",0],
        ["Egypt",0],
        ["Slovenia",0],
        ["Mexico",0],
        ["Belarus",0],
        ["Slovakia",0],
        ["Sri Lanka",0],
        ["Croatia",0],
        ["Philippines",0],
        ["Bangladesh",0],
        ["Turkey",0],
        ["Romania",0],
        ["Italy",0],
        ["South Africa",0],
        ["Hungary",0],
        ["Pakistan",0],
        ["Portugal",0],
        ["Ukraine",0],
        ["Greece",0],
        ["Oman",0],
        ["Argentina",0],
        ["Singapore",0],
        ["Bulgaria",0],
        ["Japan",0],
        ["Czech Republic",0],
        ["Ireland",0],
        ["China",0],
        ["Finland",0],
        ["Brazil",0],
        ["Norway",0],
        ["Austria",0],
        ["Denmark",0],
        ["Belgium",0],
        ["New Zealand",0],
        ["Spain",0],
        ["Switzerland",0],
        ["Russia",0],
        ["Poland",0],
        ["Israel",0],
        ["Sweden",0],
        ["Netherlands",0],
        ["France",0],
        ["Australia",0],
        ["Canada",0],
        ["India",0],
        ["Germany",0],
        ["United Kingdom",0],
        ["United States",0],
        ["Greenland",0],
        ["South Sudan",0],
        ["Chad",0],
        ["Mali",0],
        ["Unknown",1],
    ]);
    var options = {
        backgroundColor: "#3a3a3a",
        legend: false,
        colorAxis: {
            minValue: 0,
            colors: ["#f5f5f5", "#af4b4b"]
        }
    };
    var chart = new google.visualization.GeoChart(document.getElementById('map'));

    google.visualization.events.addListener(chart, "select", function() {
        for(var i=0; i<data.getNumberOfRows(); i++) {
            if(i === chart.getSelection()[0].row) {
                data.setValue(i, 1, 100);
                document.getElementById("countries-list").innerHTML += data.getFormattedValue(i, 0) + "&nbsp; &nbsp;";
            }
        }
        chart.draw(data, options);
    });
    chart.draw(data, options);
}
